### ISSUE TITLE
quote_ifneeded breaks __user

### ISSUE THREAD

**Issue by 4nd3r** [cdist-community/cdist-conf#21]
```sh
$ echo __user kaka --gid users | cdist config -i - localhost
INFO: [17229]: localhost: Starting configuration run
INFO: [17229]: localhost: Processing __user/kaka

--8<--SNIP--8<--

code-remote:stderr
------------------
useradd: group ''users'' does not exist
```

Introduced with #14.

Do we actually want this function? It's user input and we should fail if it's invalid (according to some standards) and not produce unwanted outcome (constructing name which user did not want).

Good overview of situation: https://systemd.io/USER_NAMES/

**Comment by sideeffect42** [comment]
This is indeed a bug that was introduced with #14. Some values were already quoted. This led `quote_ifneeded` to quote it again to preserve the quotes in the argument.

In #23 I removed the manual quotes.
It is disputable if `quote_ifneeded` is required for some arguments (like user or group names), but this type has parameters (e.g. `--password`, `--comment`) where special characters are to be expected.  
I would like to keep `quote_ifneeded` because it can be passed `$@` and does the quoting where needed.
